version: "3.7"
services:
  apimongo:
    image: mongo
    hostname: apimongo
    container_name: apimongo
    restart: unless-stopped
    volumes:
      - $PWD/server/data/:/data/db
    expose:
      - 27017
  api:
    build: $PWD/server
    hostname: api
    container_name: api
    restart: unless-stopped
    links:
      - apimongo
    depends_on:
      - apimongo
    ports:
      - 9527:9527
    volumes:
      - $PWD/server:/usr/src/app/
    env_file:
      - ./server/.env
    command: ["sh", "init.sh"]
