version: "3"
services:
  apimongo:
    image: bitnami/mongodb:latest
    hostname: apimongo
    container_name: apimongo
    restart: unless-stopped
    ports:
      - 27017
  api:
    build: .
    hostname: api
    container_name: api
    restart: unless-stopped
    links:
      - apimongo
    depends_on:
      - apimongo
    ports:
      - 9527:9527
    volumes:
      - $PWD:/usr/src/app/
    env_file:
      - .env
